### ISSUE TITLE
Incompatible with GCC

### ISSUE THREAD

**Issue by j00ch** [mhQuake/MHQuakeSpasm#5]
While trying to build this on Linux, i got a ton of errors. Starting with "mathlib.h" on line 83 i found:

`__declspec(align(16)) typedef union _QMATRIX {`

Stuff like that isn't going to work with GCC, read this: [https://gcc.gnu.org/wiki/Visibility](https://gcc.gnu.org/wiki/Visibility)

**Comment by mhQuake** [comment]
I haven't bothered maintaining Linux/GCC compatibility - you'll find that the makefiles are also out of date regarding which source files to include in the project.  To be honest, I'll give you the reply that everybody used to tell me when they were *demanding* Linux builds from me years ago: "it's so easy!" - or in other words, if you're going to be building on Linux you really should be able to fix these things up for yourself.  Closing this one as "won't fix".  (I don't mean to be rude, but I do have bitter experience of dealing with Linux advocates demands.)

**Comment by j00ch** [comment]
Not really an advocate of anything really, although i do believe sticking to open source standards makes for a better world. For the record, GCC isn't Linux. GCC made Linux possible, because it was free and open source. Being open source, GCC is also available for Windows.
Currently investigating cross compile tools, as that would be the easiest solution to build (if it works).
